import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
For the source, see the plugin's repository.
*/
`;

const prod = process.argv[2] === "production";

// Dev convenience: point the build output at a test vault's plugin folder via
//   INTERLINEAR_OUTDIR=/path/to/vault/.obsidian/plugins/interlinear npm run dev
// Defaults to the repo root.
const outdir =
  process.env.INTERLINEAR_OUTDIR && process.env.INTERLINEAR_OUTDIR.length > 0
    ? process.env.INTERLINEAR_OUTDIR
    : ".";

fs.mkdirSync(outdir, { recursive: true });

// Keep manifest + styles next to main.js when building into a vault folder.
function copyAssets() {
  if (path.resolve(outdir) === path.resolve(".")) return;
  for (const file of ["manifest.json", "styles.css"]) {
    if (fs.existsSync(file)) fs.copyFileSync(file, path.join(outdir, file));
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // `obsidian` and the editor packages are injected by Obsidian at runtime —
  // they MUST stay external or the plugin breaks once loaded.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outdir, "main.js"),
  minify: prod,
});

if (prod) {
  await context.rebuild();
  copyAssets();
  await context.dispose();
} else {
  copyAssets();
  await context.watch();
}
